version: "3.3"

services:
  mysql:
    container_name: d3code-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "43060:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-d3code}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    command: --lower_case_table_names=1
    volumes:
      - mysql:/var/lib/mysql/
      - ./sql/d3code.sql:/docker-entrypoint-initdb.d/d3code.sql:ro
      - ./sql/quartz.sql:/docker-entrypoint-initdb.d/quartz.sql:ro

  redis:
    container_name: d3code-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "46379:6379"
    volumes:
      - redis:/data

  phpmyadmin:
    container_name: d3code-phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: d3code-mysql
    ports:
      - "40081:80"
    depends_on:
      - mysql

  server:
    container_name: d3code-server
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "48080:8080"
    environment:
      # https://github.com/polovyivan/docker-pass-configs-to-container
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS:
        ${JAVA_OPTS:-
        -Xms512m
        -Xmx1024m
        -XX:MetaspaceSize=256m
        -XX:MaxMetaspaceSize=512m
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:+PrintGCDateStamps
        -XX:+PrintGCDetails
        -XX:NewRatio=1
        -XX:SurvivorRatio=30
        -XX:+UseParallelGC
        -XX:+UseParallelOldGC
        -Djava.security.egd=file:/dev/./urandom
        }
      ARGS:
        --spring.datasource.dynamic.datasource.master.url=${MASTER_DATASOURCE_URL:-jdbc:mysql://d3code-mysql:3306/d3code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.dynamic.datasource.master.username=${MASTER_DATASOURCE_USERNAME:-root}
        --spring.datasource.dynamic.datasource.master.password=${MASTER_DATASOURCE_PASSWORD:-123456}
        --spring.datasource.dynamic.datasource.slave.url=${SLAVE_DATASOURCE_URL:-jdbc:mysql://d3code-mysql:3306/d3code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.dynamic.datasource.slave.username=${SLAVE_DATASOURCE_USERNAME:-root}
        --spring.datasource.dynamic.datasource.slave.password=${SLAVE_DATASOURCE_PASSWORD:-123456}
        --spring.redis.host=${REDIS_HOST:-d3code-redis}
    depends_on:
      - mysql
      - redis

  admin:
    container_name: d3code-admin
    build:
      context: ./admin
    restart: unless-stopped
    ports:
      - "40080:80"
    depends_on:
      - server

volumes:
  mysql:
    driver: local
  redis:
    driver: local
