# 项目相关配置
d3code:
  # 名称
  name: d3code
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 扫描的mapper
  # auto-scan-mapper: com.alphay.boot.**.mapper,;com.d3code.**.mapper
  auto-scan-mapper: com.alphay.boot.**.mapper
  # 扫描的目录
  # auto-scan-package: com.alphay.boot,;com.d3code
  auto-scan-package: com.alphay.boot
  # 验证码类型
  captcha-type: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.alphay: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  mvc:
    pathmatch:
      # 修改MVC匹配机制
      matching-strategy: ANT_PATH_MATCHER
  autoconfigure:
    # 排除druid自动配置
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: tldzqjysvduqsdybnnldbkksfgpbglcqfhujbqbxbcbgdtabfophxxtdpzmuanqjlqwkqihpujdlsfqbztxwmzrdpglmreshlfkyljizkrvbthwewgpqoendfloxxhclyzdilcepdafzofizibjyslguddpynoahwkszqkggxqyxpggsdcmtufnvbipmrzoakcnyygzdqnpdlzjhgbhihnlbwlbvzjlmfazvnfpdmdesnxqthgedqrcrbdonqxukbyytioprcafttuvpwrpucfmxulvalvkcwfnjmavqgrvzaxqeuthltoxkwiziwadjpihyzwpyotttiyrmmbochmtvjdahnwtovmnqzvsvvtroyjqyefqrqgohrlfrmdivpfgktgzxqvoucejsxbretmqbjspdkgxaviqgkkdhecdvltuxanijbneqmglnlrlhwoyifswczglftjcbaydpfcklqpgtbavhvatwrfrcnftpeqcnokoitvgmrogkxnvo
  # 令牌有效期（默认30分钟）
  expireTime: 30

# Mybatis配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-executor-type: SIMPLE
  #type-aliases-package: com.alphay.boot.**.domain,;com.d3code.**.domain
  type-aliases-package: com.alphay.boot.**.domain

# PageHelper分页插件
pagehelper:
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 工作流 Flowable 配置
flowable:
  # 1. false: 默认值，Flowable 启动时，对比数据库表中保存的版本，如果不匹配。将抛出异常
  # 2. true: 启动时会对数据库中所有表进行更新操作，如果表存在，不做处理，反之，自动创建表
  # 3. create_drop: 启动时自动创建表，关闭时自动删除表
  # 4. drop_create: 启动时，删除旧表，再创建新表
  database-schema-update: true # 设置为 false，可通过 https://github.com/flowable/flowable-sql 初始化
  db-history-used: true # flowable6 默认 true 生成信息表，无需手动设置
  check-process-definitions: false # 设置为 false，禁用 /resources/processes 自动部署 BPMN XML 流程
  history-level: full # full：保存历史数据的最高级别，可保存全部流程相关细节，包括流程流转各节点参数

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
